# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 74b0ae6c28e0f1c4cb99dc92b1060d20f64b2edcdd8c2ca13bd1655ef857ed44aa82a1893ca27514a44c2779162f23ad3e5f517a5c39cb65ebc1fae9868d44cb

test:
  secret_key_base: 1c49800cd284b18ba3e6002c465ca50da3c74b1f715a001ce5f205dbb394b78cce23da2454a5aecb7e72cc07746dcbca4e5b8b459158637da5e09b30310099c5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
